### ISSUE TITLE
MaStRMirror fails when docker container is not avalailable

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#165]
If the docker container is not running it will be initialized by executing docker-compose. This takes a second which let subsequent queries fails. See the log

```
Creating network "open-mastr_default" with the default driver
stat /var/lib/docker/overlay2/d16d033e826342cefe47744354c969d049d8f5f53497903491889c4be88fbd87: no such file or directory
Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/guido/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 55443?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guido/git/open-MaStR/playground_mirror.py", line 15, in <module>
    parallel_processes=6,
  File "/home/guido/git/open-MaStR/open_mastr/soap_api/prototype_mastr_reflected.py", line 45, in __init__
    with engine.connect().execution_options(autocommit=True) as con:
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2265, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2372, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2342, in _wrap_pool_connect
    e, dialect, self
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/guido/miniconda3/envs/py36_open_mastr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/guido/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 55443?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

For reproduction: `docker-compose down -v`

**Comment by chrwm** [comment]
Possibly reopen the issue if the error is raised again.
