### ISSUE TITLE
Updating with soap_API does not work

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#229]
On my machine, I can't update the sqlite DB with the soap_API after downloading the xml-dump. So I just wanted to check whether that's a local problem or if you run into the same bug?

This is the error message

```
/home/cwm/Python/open-mastr/open_mastr/mastr.py:288: UserWarning: For method = 'API', bulk download related parameters (with prefix bulk_) are ignored.
  warn(
2022-05-03 09:07:18,827 [INFO] Backfill data for technology wind
2022-05-03 09:07:18,828 [INFO] Insert basic unit data into DB and submit additional data requests
2022-05-03 09:07:18,828 [INFO] Get list of units with basic information for technology wind (Wind)
Get basic Einheiten data informationfor technology wind (Wind): 0 units [00:26, ? units/s]
2022-05-03 09:07:45,363 [ERROR] Finally failed to download data.Basic unit data of index 1 to 10 will be missing.
Traceback (most recent call last):
  File "/home/cwm/Python/open-mastr/open_mastr/mastr_DL.py", line 25, in <module>
    db.download(method="API", api_date='latest', api_limit=10, technology=technology, api_data_types=api_data_types, api_location_types=api_location_types)
  File "/home/cwm/Python/open-mastr/open_mastr/mastr.py", line 208, in download
    mastr_mirror.backfill_basic(technology, limit=api_limit, date=api_date)
  File "/home/cwm/Python/open-mastr/open_mastr/soap_api/mirror.py", line 424, in backfill_basic
    ids_to_delete = [_["EinheitMastrNummer"] for _ in inserted_and_updated]
UnboundLocalError: local variable 'inserted_and_updated' referenced before assignment

Process finished with exit code 1

```

**Comment by chrwm** [comment]
After further troubleshooting, I now believe it is a problem with the API. Could you check if you could download via the API?

**Comment by FlorianK13** [comment]
I get the following error:


```Downloading with soap_API.

   -- Settings --
units after date: 2022-04-27 00:00:00
unit download limit per technology: 2
parallel_processes: None
chunksize: 1000
technologies: ['solar']
data_types: ['unit_data', 'eeg_data', 'kwk_data', 'permit_data']
location_types: None
2022-05-03 15:13:42,283 [INFO] Backfill data for technology solar
2022-05-03 15:13:42,285 [INFO] Insert basic unit data into DB and submit additional data requests
2022-05-03 15:13:42,285 [INFO] Get list of units with basic information for technology solar (SolareStrahlungsenergie)
Get basic Einheiten data informationfor technology solar (SolareStrahlungsenergie): 0 units [00:00, ? units/s]Traceback (most recent call last):
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: basic_units.DatumLetzteAktualisierung

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kotthoff\Documents\Projekte\eTwin\github\open_mastr_manual_test.py", line 27, in <module>
    db.download(
  File "c:\users\kotthoff\documents\projekte\etwin\github\open-mastr\open-mastr\open_mastr\mastr.py", line 208, in download
    mastr_mirror.backfill_basic(technology, limit=api_limit, date=api_date)
  File "c:\users\kotthoff\documents\projekte\etwin\github\open-mastr\open-mastr\open_mastr\soap_api\mirror.py", line 328, in backfill_basic
    if session.query(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\orm\query.py", line 2879, in scalar
    ret = self.one()
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\orm\query.py", line 2856, in one
    return self._iter().one()
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\orm\query.py", line 2894, in _iter
    result = self.session.execute(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\orm\session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\sql\elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\kotthoff\Anaconda3\envs\mastr\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: basic_units.DatumLetzteAktualisierung
[SQL: SELECT EXISTS (SELECT *
FROM basic_units
WHERE basic_units."EinheitMastrNummer" = ? AND basic_units."DatumLetzteAktualisierung" < ?) AS anon_1]
[parameters: ('SEE961913293746', '2022-04-28 05:36:51.011907')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Get basic Einheiten data informationfor technology solar (SolareStrahlungsenergie): 0 units [00:03, ? units/s]
```

**Comment by Ludee** [comment]
Mine is:
```Traceback (most recent call last):
File "D:/git/github/OpenEnergyPlatform/open-MaStR/[main.py](http://main.py/)", line 29, in <module>
[db.download](http://db.download/)(method="API",
File "D:\git\github\OpenEnergyPlatform\open-MaStR\open_mastr\[mastr.py](http://mastr.py/)", line 214, in download
mastr_mirror.retrieve_additional_data(
File "D:\git\github\OpenEnergyPlatform\open-MaStR\open_mastr\soap_api\[mirror.py](http://mirror.py/)", line 620, in retrieve_additional_data
if chunksize > limit:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Process finished with exit code 1```

**Comment by chrwm** [comment]
@Ludee [5318301](https://github.com/OpenEnergyPlatform/open-MaStR/commit/5318301c1c8454c239818f534522dbed4f4ae4aa) this should fix your error message.

**Comment by chrwm** [comment]
@FlorianK13 your error:

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: basic_units.DatumLetzteAktualisierung

it seems like you could still have an old SQLite DB that contains a typo in the column name in the `basic_unit table` -> "DatumLetzeAktualisierung"

@deniztepe changed the column name in 76604074. 

I think setting up a new SQLite DB could fix it if you haven't done so since Deniz's commit. Let me know if this fixes it.

**Comment by FlorianK13** [comment]
@chrwm Yes, I deleted the data base and downloaded it again. No The bug is gone.

**Comment by chrwm** [comment]
Ok, so this means you can successfully update the SQlite DB with the soap_API with all `technologies`?

**Comment by FlorianK13** [comment]
Yes, it runs for all `technologies`.

**Comment by deniztepe** [comment]
It seems to be the case also on my computer.

**Comment by chrwm** [comment]
For me, too. Somehow, my credentials were corrupted.

**Comment by FlorianK13** [comment]
Within Get basic Lokationen the download does not work with the API. It takes more than five minutes to download two units.

@chrwm I think you mentioned that you are aware of some bug there?

`Downloading with soap_API.

   -- Settings --
units after date: 2022-05-05 00:00:00
unit download limit per technology: 2
parallel_processes: None
chunksize: 1000
technologies: ['solar']
data_types: ['unit_data', 'eeg_data', 'kwk_data', 'permit_data']
location_types: None
2022-05-10 10:50:28,463 [INFO] Backfill data for technology solar
2022-05-10 10:50:28,473 [INFO] Insert basic unit data into DB and submit additional data requests
2022-05-10 10:50:28,474 [INFO] Get list of units with basic information for technology solar (SolareStrahlungsenergie)
Get basic Einheiten data information for technology solar (SolareStrahlungsenergie): 2 units [00:03,  1.80s/ units]
2022-05-10 10:50:32,094 [INFO] Backfill successfully finished
2022-05-10 10:50:32,099 [INFO] No further data is requested
2022-05-10 10:50:32,104 [INFO] No further data is requested
2022-05-10 10:50:32,109 [INFO] No further data is requested
2022-05-10 10:50:32,114 [INFO] No further data is requested
Get basic Lokationen data information: 0 units [00:00, ? units/s]2022-05-10 10:56:00,210 [ERROR] Finally failed to download data.Basic unit data of index 1 to 2 will be missing.
Get basic Lokationen data information: 0 units [05:28, ? units/s]`

**Comment by chrwm** [comment]
I haven't encountered a very long downloading time for location data yet. However, after running the script three times for testing purposes, one time took exceptionally long. For now, I suspect the API itself.  Let me know if the problem is occurring more frequently.

**Comment by Ludee** [comment]
![grafik](https://user-images.githubusercontent.com/14353512/167705780-104eda64-8b55-41e5-b163-546a38c1e217.png)

**Comment by Ludee** [comment]
Not a good time to test the release.
