### ISSUE TITLE
Error when creating clean csv's

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#260]
When creating clean csv's, the function throws an error and aborts.

```
Traceback (most recent call last):
  File "/home/cwm/Python/open-mastr/main.py", line 118, in <module>
    cleaned = cleaned_data()
  File "/home/cwm/Python/open-mastr/postprocessing/cleaning.py", line 30, in cleaned_data
    save_cleaned_data(raw_filtered)
  File "/home/cwm/Python/open-mastr/open_mastr/data_io.py", line 120, in save_cleaned_data
    if dat["DatumLetzteAktualisierung"].max() > newest_date:
  File "pandas/_libs/tslibs/timestamps.pyx", line 199, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__
TypeError: can't compare offset-naive and offset-aware datetimes
```
https://github.com/OpenEnergyPlatform/open-MaStR/blob/965978d15d6d349f7c3ed56e787d0fce87031757/open_mastr/data_io.py#L112-L122

**Comment by chrwm** [comment]
The error stems from comparing a `naive` python datetime object to an `aware` datetime object. The if statement will always be True; hence the comparison can be omitted.
