### ISSUE TITLE
Download fails: TypeError: object cannot be converted to an IntegerDtype

### ISSUE THREAD

**Issue by rumo123** [OpenEnergyPlatform/open-MaStR#314]
Dear all,

im trying to make use of the bulk download of the mastr and export it as .csv, but I keep getting an error. This is all the code im using:

from open_mastr import Mastr
db = Mastr()
db.download()

It downloads the xml and it parses and cleanses the files one by one. It works at first, but at some point (EinheitenStromSpeicher_1.xml) it breaks, saying: TypeError: object cannot be converted to an IntegerDtype

Do I have to do more preprocessing myself? Would that code normally be sufficient to get the .csv? Do you have an Idea what the Issue might be? Im not very familiar with the xml format, so Id be happy if I dont have to modify the files one by one...

Anyway, help is much appreciated!

Im using open-mastr 0.11.4

Best wishes, Elias

Full traceback:

File 'EinheitenSolar_25.xml' is parsed.
Data is cleansed.
297 entries already existed in the database.
Table 'storage_extended' is filled with data 'einheitenstromspeicher' from the bulk download. 
File 'EinheitenStromSpeicher_1.xml' is parsed.
Traceback (most recent call last):

  File "... line 11, in <module>    db.download()

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\mastr.py", line 189, in download
    convert_mastr_xml_to_sqlite(

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\xml_download\utils_write_sqlite.py", line 82, in convert_mastr_xml_to_sqlite
    df = prepare_table_to_sqlite_database(

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\xml_download\utils_write_sqlite.py", line 154, in prepare_table_to_sqlite_database
    df = add_zero_as_first_character_for_too_short_string(

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\xml_download\utils_write_sqlite.py", line 221, in add_zero_as_first_character_for_too_short_string
    df[column_name] = df[column_name].astype("Int64").astype(str)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\dtypes\cast.py", line 1105, in astype_nansafe
    return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\arrays\integer.py", line 323, in _from_sequence
    values, mask = coerce_to_array(scalars, dtype=dtype, copy=copy)

  File "...\AppData\Roaming\Python\Python38\site-packages\pandas\core\arrays\integer.py", line 198, in coerce_to_array
    raise TypeError(f"{values.dtype} cannot be converted to an IntegerDtype")

TypeError: object cannot be converted to an IntegerDtype

**Comment by FlorianK13** [comment]
Thanks for your bug report.
One problem of our work is that the files that are downloaded from BNetzA change each day, so an error in the files can appear that makes our pipeline fail.
I will try to reproduce your bug and see what I can do.

**Comment by FlorianK13** [comment]
@rumo123 apparently I was not able to reproduce the error. 
I think the reason is the following: The files you download from marktstammdatenregister.de change every day, so probably the file from yesterday was corrupted. Can you run the following code today:

from open_mastr import Mastr
db = Mastr()
db.download(technology=["storage"])

This should download todays files and write them to the sqlite database. With technology=["storage"] you only write the storage files to the database. That is where your error occured.

If the error still appears can you please provide us with your python version and your pandas version?

**Comment by rumo123** [comment]
I was able to get past the faulty files after seeing post #319. It was the "A-" in the PLZ column which caused the error. For now, I just deleted them all and was able to save the data to the sql.

But im still struggling with the very basic problem of saving it as a .csv. As I understood, the db.download() uses the bulk download and stores it to the sql and the db.to_csv() uses the online API and saves it to .csv, right? How would I save the bulk download to .csv?

This is the error im getting when using db.to_csv("storage")


Technology tables: ['storage']

are saved to: ...\.open-MaStR\data\dataversion-2022-05-16_AB_rli
...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\data_io.py:227: DtypeWarning: Columns (13,37,39,51,52,54,63,64,65,77,87,88,89,90,106,107,108,109,110,111,112,113,114,115,119,120,121) have mixed types.Specify dtype option on import or set low_memory=False.
  raw = read_csv_data("raw")
Traceback (most recent call last):

  File "...\untitled3.py", line 11, in <module>
    db.to_csv("storage")

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\mastr.py", line 333, in to_csv
    cleaned_data()

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\data_io.py", line 233, in cleaned_data
    save_cleaned_data(raw_filtered)

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\data_io.py", line 124, in save_cleaned_data
    metadata = datapackage_meta_json(newest_date, data.keys(), data=["raw", "cleaned"], json_serialize=False)

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\soap_api\metadata\create.py", line 215, in datapackage_meta_json
    datapackage_base_dict = datapackag_base(

  File "...\.conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\soap_api\metadata\create.py", line 87, in datapackag_base
    "referenceDate": reference_date.strftime("%Y-%m-%d %H:%M:%S"),

AttributeError: 'float' object has no attribute 'strftime'

**Comment by FlorianK13** [comment]
We are working on it and try to get a new release as soon as possible (#315) 

_File "....conda\envs\Open-Mastr\lib\site-packages\open_mastr-0.11.4-py3.8.egg\open_mastr\mastr.py", line 333, in to_csv
cleaned_data()_

The cleaned_data function that causes an error for you will be deleted in the new release as it is more of an artefact from earlier times (see #318). If you do not want to wait until the release you can comment the call of cleaned_data in mastr.py on your own and run the code again.

**Comment by FlorianK13** [comment]
@rumo123 We have released v0.11.6, you can install it with `pip install --upgrade open-mastr`
There the errors should not show up again.
