### ISSUE TITLE
technology_input_harmonisation cannot handle technology=None

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#323]
`technology` is assumed to be a list for `method`="API". The default value of None causes an error.

Traceback (most recent call last):
  File "C:\Users\kotthoff\Documents\Projekte\eTwin\github\open_mastr_manual_test.py", line 65, in <module>
    db.download(
  File "c:\users\kotthoff\documents\projekte\etwin\github\open-mastr\open-mastr\open_mastr\mastr.py", line 186, in download
    ) = technology_input_harmonisation(
  File "c:\users\kotthoff\documents\projekte\etwin\github\open-mastr\open-mastr\open_mastr\utils\helpers.py", line 293, in technology_input_harmonisation
    if "permit" in technology:
TypeError: argument of type 'NoneType' is not iterable

**Comment by FlorianK13** [comment]
Solved in v0.11.6
