### ISSUE TITLE
Cant save technology="market" as .csv  ("Table has invalid string")

### ISSUE THREAD

**Issue by EliasAlthoff** [OpenEnergyPlatform/open-MaStR#350]
Dear all,

Im having an Issue downloading the "market" section of the mastr. Downloading worked fine, the cleansing as well. But when Im trying to save it as a .csv, I get this errror:

from open_mastr import Mastr

db = Mastr()
db.download(technology=['market'])
db.to_csv('market')

File 'Marktakteure_23.xml' is parsed.
Data is cleansed.
Table 'market_roles' is filled with data 'marktrollen' from the bulk download.
File 'Marktrollen.xml' is parsed.
Data is cleansed.
Bulk download and data cleansing were successful.
Traceback (most recent call last):

  File ".conda\envs\open_mastr_import\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "...mastr\download_mastr.py", line 14, in <module>
    db.to_csv('market')

  File "...\.conda\envs\open_mastr_import\lib\site-packages\open_mastr\mastr.py", line 325, in to_csv
    raise ValueError("Tables parameter has an invalid string!")

ValueError: Tables parameter has an invalid string!

Im using v0.11.7

Downloading and saving the combustion file worked fine.

best wishes,
Elias

**Comment by EliasAlthoff** [comment]
I found my mistake, its: 
db.to_csv('market_actors') instead of db.to_csv('market')
